parameters:
#    rmt_time_scheduling_weekly_grid.example.class: RMT\TimeScheduling\WeeklyGridBundle\Example

services:
    weekly_grid.configure_menu_listener:
        class: RMT\TimeScheduling\WeeklyGridBundle\Menu\ConfigureMenuListener
        tags:
          - { name: kernel.event_listener, event: menu.user_menu_configure, method: onMenuConfigure }
